version: '2'

services:
  db:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
 
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

volumes:
  postgres:
